### ISSUE TITLE
Script repo should auto detect type

### ISSUE THREAD

**Issue by HarshKhandeparkar** [HarshKhandeparkar/bashinthebin#29]
This script should automatically detect whether the given argument is a ppa or a link.
If the link has nothing but `ppa/package` then it should add `ppa:` automatically.

**Comment by niravasher** [comment]
Can this be used for ubuntu? @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
@niravasher this is specifically created for Ubuntu and Ubuntu like systems(Debian based)

**Comment by HarshKhandeparkar** [comment]
@niravasher this is specifically created for Ubuntu and Ubuntu like systems(Debian based)

**Comment by HarshKhandeparkar** [comment]
@niravasher this is specifically created for Ubuntu and Ubuntu like systems(Debian based). So yes, it can be used.
